FROM node:16.13.0-alpine As Builder

RUN npm config set unsafe-perm true

COPY ./package*.json /usr/build/
WORKDIR /usr/build
RUN npm ci

COPY ./ /usr/build/
#COPY ./public /usr/build/
RUN npm run build

CMD ["npm", "start"]